### ISSUE TITLE
Congratulations :-)

### ISSUE THREAD

**Issue by rdebath** [lactzy/c-brainfuck#1]
Your brainfuck interpreter is able to successfully run this "Hello World" but it is still broken...

```brainfuck
>++++++++[-<+++++++++>]<.>>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.>->
+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

This is quite unusual, unfortunately, this means that I only have [this brainfuck program](https://github.com/rdebath/Brainfuck/blob/master/bitwidth.b) as a test case.

Luckily your program does seem to fail quite early with this code (which should do nothing):
```brainfuck
[+++++++.+++.][<-->]
```

Here are some [archive](http://esoteric.voxelperfect.net/files/brainfuck/src/) [programs](https://github.com/rdebath/Brainfuck/tree/master/testing) for your testing. 

PS: Thank you for the extra test case for my program.

**Comment by lactzy** [comment]
To be honest, I'd have been suprised if my interpreter didn't produce any more errors :D

The point of this project at my university was to write a simple BF interpreter, which would be considered working if it runs and displays the Sierpiński-triangle correctly. Its code is as follows.

[ThisprogramprintsSierpinskitriangleon80-columndisplay.]>++++[<++++++++>-]>++++++++[>++++<-]>>++>>>+>>>+<<<<<<<<<<[-[->+<]>[-<+>>>.<<]>>>[[->++++++++[>++++<-]>.<<[->+<]+>[->++++++++++<<+>]>.[-]>]]+<<<[-[->+<]+>[-<+>>>-[->+<]++>[-<->]<<<]<<<<]++++++++++.+++.[-]<]+++++*****Made*By:*NYYRIKKI*2002*****

Due to the very limited deadline and the fact that this is my first time doing anything like this, I was sure that my program is a rather modest take on a subject which is much bigger than I anticipated. But, I'd still like to continue working on it after the deadline ends, it really interests me, that's why I brought this project to Github.

Thank you for your feedback, and if you'd be able to provide some examples on which my interpreter fails or does weird things, that would help me tremendously. :)

**Comment by rdebath** [comment]
Well, in addition to many of the programs in the archives I mentioned before, this updated version of my test program should print "Hello World!" 

```brainfuck
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

**Comment by lactzy** [comment]
Oh I see.

I've had a similar problem before with a "[-.]" in front of the triangle code, it entered the loop even though it shouldn't have, overflowed the first byte, printed out all ASCII characters from 255 to 0, then when it reached 0 again, it'd draw the triangle. This looks very similar.

    ++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.------.--------.>+.>.

Interestingly enough, this Hello World works just fine. Will have to investigate, thanks for your help! :)
